branch-defaults:
  default:
    environment: crisisline-prod
    group_suffix: null
environment-defaults:
  crisisline-prod:
    branch: null
    repository: null
global:
  application_name: crisisline
  branch: null
  default_ec2_keyname: crisislinekey_prod
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
